### ISSUE TITLE
Regex who_pattern for zone_who_name

### ISSUE THREAD

**Issue by CodeArc13** [CodeArc13/PyDWMG#14]
and find code

**Comment by CodeArc13** [comment]
Could this be done in zone_pattern by using a possible OR operation in the regex so it detects zone and who in one pattern?

**Comment by CodeArc13** [comment]
All possible format examples of /who results I can find are:-
[Tue Feb 09 08:44:00 2021] There are 12 players in South Karana.
[Tue Feb 09 08:43:22 2021] There are no players in EverQuest that match those who filters.
[Mon Nov 11 22:55:11 2019] There are 18 players in EverQuest.

**Comment by CodeArc13** [comment]
So with log examples of above comment we would want to have it ignore anything that has EverQuest so it only matches actual zone names.

**Comment by mmlakin** [comment]
Have you tested for only 1 player?  Does it change `are` to `is` and `players` to `player`?  This regex should work for all those cases:
`^\[.*\] There (are|is) [\d]+ player[s]* in (?!EverQuest).*\.$`

Check it in action here (temporary link, might be dead when you view this):
https://regexr.com/5n6gs

**Comment by CodeArc13** [comment]
I was playing with regexr, nice site, and that looks like the exact code we need for who but I was wondering if it could be combined with zone entering so we could detect zone and who in one pattern, or is this too complex?

**Comment by CodeArc13** [comment]
You are right it does change for one player:
[Tue Nov 12 18:58:18 2019] There is 1 player in Surefall Glade.

**Comment by CodeArc13** [comment]
Just tested that regex on a test python script it seems to return "are" and "is" instead of the zone name and doesn't have the zone name in a second list indices or even a second empty list indices.

**Comment by CodeArc13** [comment]
`^\[.*\] There (?:are|is) [\d]+ player[s]* in (?!EverQuest).*\.$`

are and is need to be a non-capturing group or they are returned as list results, the problem now is that matches now return the entire log line.

**Comment by mmlakin** [comment]
ah yea, I forgot how we were actually using it in the code lol we'll need to capture the zone name, and if it's not "EverQuest" then treat it as valid and return it
`^\[.*\] There (?:are|is) [\d]+ player[s]* in (.*)\.$`

As for checking against two patterns, we can just check it twice and check the result each time... we could get clever with it and write something like this:
```
for match in map(lambda pattern: re.findall(pattern, log_line), regex_patterns):
    if match != []:
        zone_name = match[0]
        if zone_name != "EverQuest":
            signal.emit(zone_name)
        break
```
but we really don't have a large number of patterns to match against and it's definitely harder to read than a couple if/then statements.

**Comment by CodeArc13** [comment]
Yes, using an if statement to determine if the result is "EverQuest" is how the VB version works

**Comment by CodeArc13** [comment]
Does this lambda statement need some kind of list of regex patterns to loop through?

**Comment by mmlakin** [comment]
yea, regex_patterns would be a list containing regex pattern strings

**Comment by mmlakin** [comment]
one question though, do we really need to be able to detect zone from who messages when we can just read the `You have entered ZONE` log message?  won't this message *always* exist, as every method of changing zone (zone, gate, die) records that log?  I've seen using /who as a shortcut to update DWMG mid-run, but if it reads current zone on startup, do we need this feature?

**Comment by CodeArc13** [comment]
It was just a feature I added to the VB version to change the map using /who or / from eq but its probably pretty un-intuative.

**Comment by mmlakin** [comment]
Let's close this issue?  I don't think we should add this feature, let's just say you have to change zone once after enabling logging for it to track your current zone

**Comment by CodeArc13** [comment]
Ye we will want manual zone selection eventually so users can see who on the mapping server is in what zone, (also maybe a selection of chars/alts to go to the zone each char is in), so we can just let the user set it back to their current zone and also maybe a button in DWMG that sets the map to the current zone, the /who idea was basically an idea for allowing command line interfacing from EQ a bit like discord bots have.
