### ISSUE TITLE
Current loc drawing on map

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#15]
Basic plotting of current location on the map

**Comment by CodeArc13** [comment]
Researching pyQT5 animation/drawing deciding which method is best, its a little alien too me but I think once worked out the basics it shouldn't be too bad to modify to what we want.

**Comment by mmlakin** [comment]
Wanna post links to any docs you're reading?

**Comment by CodeArc13** [comment]
Sure thing, I looked into pyQT5 animation but that seems to be for timed animations/conventional animations.  I have found something that may be more in our use case that is:- QGraphicsView, QGraphicsScene, and QGraphics-Item.

Read this short article and see what you think, it's a lot more complicated than the GDI+ version in VB but I think it will have more functionality in the long run. https://www.pythonstudio.us/pyqt-programming/itembased-graphics.html

**Comment by CodeArc13** [comment]
I think it will let us composite an image, it supports a background layer and ordering on the Z-axis for all layers, what we want is to be able to have a static background image and the ability to refresh the image with new locations without leaving old locs which would form a trail.

**Comment by CodeArc13** [comment]
I think this Tic Tac Toe example might have a lot of what we need https://github.com/mmisono/pyqt5-example/blob/master/tic_tac_toe.py just got to work out how to put a background image in the scene.
