### ISSUE TITLE
Casting or rounding up/down floats to integers when plotting to map

### ISSUE THREAD

**Issue by CodeArc13** [CodeArc13/PyDWMG#19]
We need to either cast and truncate or round the float calculations to integers as python is giving a depreciation warning for implicit casting.  Rounding may be more accurate, we will have to test.

**Comment by mmlakin** [comment]
I think in this case, displaying a coordinate on a grid, rounding will be the most accurate and there is no math or algorithm that will require using floor instead of just rounding up/down

**Comment by CodeArc13** [comment]
Looking at the VB version all coords seem to be in floats, so I guess when writing to the screen its just casting/truncating implicitly to int.  I might have decided back then that if a value fell inside a given pixel that that was the pixel it is supposed to be and not the next or previous one,  It probably doesn't make much difference but we can experiment with this if we notice a discrepancy later.

**Comment by mmlakin** [comment]
I don't understand, what would we experiment with and how would we notice a discrepancy?

**Comment by CodeArc13** [comment]
Well, experimenting with either rounding up/down or just straight casting to int/ignoring the decimal value.  The inaccuracy of rounding might be an issue where say X = 5.7 so it should fall in the 5th pixel but rounding makes it 6 so in effect moving the marker too far to the right, its a tiny discrepancy but if we ever implement a zooming feature or the zone the player is in is quite small it might be noticeable.  As I said its probably nothing to worry about and trivial to alter the code later.

**Comment by CodeArc13** [comment]
Having said that rounding might actually be the more accurate way to go, as 5.7 might actually be better in the 6th pixel lol, but the VB code does look like its just chopping off the decimal when it plots which has never caused issues.

**Comment by CodeArc13** [comment]
Trivial
