### ISSUE TITLE
Probably don't need seperate scaled loc vars, but it does make it easier to see if the coord is scaled or not.

### ISSUE THREAD

**Issue by CodeArc13** [CodeArc13/PyDWMG#23]
As title

**Comment by mmlakin** [comment]
in the context of the draw map function, do we ever need to actually use the unscaled locs?  If not, then we don't need to keep both around and we can just scale them at the beginning and set them to px & py imo

**Comment by CodeArc13** [comment]
There's a few reasons to have separates, one being to check if previous loc is none or not after doing a shift for edge cases which always have the scaled previous locs set to 0 if they don't exist, in the VB version I just used a bunch of boolean flags to check things like this.  Also I just think it makes it easier to understand what is going on in the calculations.  We can change it later easily enough.

**Comment by CodeArc13** [comment]
Trivial to change later
