### ISSUE TITLE
Add dialog box to select EQ folder

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#28]
Allow user to select their EQ log folder via dialog box

**Comment by CodeArc13** [comment]
@mmlakin First attempt completed have a test of it, you can probably think of better ways to do this but it works, it now over writes the entire eq_logfile.txt every time a new valid folder is selected so you will have to start running the log generator from either the EQ logs folder or a logs folder of your own making and give the fake log file the 'eqlog_*.txt' file name format.
