### ISSUE TITLE
Bug - Selecting the EQ Folder instead of the Logs folder gives unexpected results/messages.

### ISSUE THREAD

**Issue by CodeArc13** [CodeArc13/PyDWMG#32]
Selecting the EQ Folder finds the log folder but displays the message :- "Please select either your EQ folder or the log folder inside it and ensure you have logging enabled and logs in the log folder."
THEN The logs folder has actually been selected which can be verified as done so by selecting the log folder its self which then displays the message:- "You've selected the log folder already in use.  If you want to change the log directory, please select a different folder."
I have made sure that the already selected message isn't being displayed as a result of the log folder being previously selected by having a second test log folder containing logs which is inside another folder which also contains eqgame.exe and setting it to that before doing this test.

**Comment by mmlakin** [comment]
I see what the problem was and this should be resolved now in the latest commit...I tested it on my mac by creating the folders and files manually and it's working as expected

**Comment by CodeArc13** [comment]
@mmlakin That seems to have fixed most of it, but now the previous log folder selected message does not come up when selecting the EQ Folder of a previously selected log folder, it only appears on the log folder its self.

**Comment by mmlakin** [comment]
Fixed by removing the warning dialog
