### ISSUE TITLE
Inconsistency with linting/fixing

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#34]
We need to sync on our autoformatting settings:

linter: flake8
fixer/autoformat: black

**Comment by CodeArc13** [comment]
@mmlakin According to this website that formats code into Black which uses the latest version of Black, the same version I am using v21.5b2 and has the default Black 88 character line length the drawEllipse line should be a block not a single line.  Which possibly means your version of Black is old or you have a setting that isn't the same as in my VSCode.

https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AFhAM1dAD2IimZxl1N_WlbvK5V8vGPqleRhaY2bUE2k5S3sYCuprYO3dDA2wDAfWxCRPuwK5GVvasW3Ll1Y1BHIZO5-Jh1h-ZTq1SoruneulReJyGK4AA-LFMsma2oPt6CJDjj1dSOegofqZ1JFqT9JN_0q1-Y5nkBhOplg6DKclO9FOWrbHN8AmF8OrCILW3Sp6v-cvIdDk7T1eGNHfxi41D6-EmjF67fpvc_AWGuvTCslDdoxxotR4FlqbdLJtdCGY9xHHjvKD5UbAK7wRkIDogAAAAAAtKlmEPG31J8AAekB4gIAAPrqjLCxxGf7AgAAAAAEWVo=

**Comment by mmlakin** [comment]
Fixed this, the drawEllipse issue was caused by a bug in my vim config which is now resolved.  Confirmed we're both using flake8 and black for Python linting/fixing.
