### ISSUE TITLE
Figure out QT slots & signals

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#4]
How to pass our log parsing function into the QT Application and have it run it as a thread

**Comment by CodeArc13** [comment]
[](https://www.learnpyqt.com/courses/concurrent-execution/multithreading-pyqt-applications-qthreadpool/)

**Comment by CodeArc13** [comment]
https://www.learnpyqt.com/courses/concurrent-execution/multithreading-pyqt-applications-qthreadpool/
