### ISSUE TITLE
Linux transparent window with taskbar & tray icon

### ISSUE THREAD

**Issue by mmlakin** [CodeArc13/PyDWMG#5]
This can be done using a control window, but then there are two windows and it's pretty ugly.

**Comment by CodeArc13** [comment]
We need a better method of doing this or a clever way to hide the main window, like making it as small as possible without losing the window registration in the window manager and keeping it 'always on bottom'.  Also the main window preview in windows 10 taskbar when hovering over the item needs to be the map window instead, I believe there is a way to access that in python directly or pyqt5.

**Comment by mmlakin** [comment]
Not important, will revisit when we have more working code
